### ISSUE TITLE
跑不起来啊

### ISSUE THREAD

**Issue by xinkong2000** [wilin52/union_tabs#4]
环境：Flutter (Channel master, 1.23.0-14.0.pre.75, on Mac OS X 10.15.6 19G2021   x86_64, locale zh-Hans-CN)
错误：
════════ Exception caught by widgets library ═══════════════════════════════
The following _CastError was thrown building NotificationListener<ScrollNotification>:
Null check operator used on a null value

The relevant error-causing widget was: 
  NotificationListener<ScrollNotification> file:///Users/。。。/.pub-cache/hosted/pub.flutter-io.cn/union_tabs-1.0.0+7/lib/src/outer/union_outer_page_view.dart:177:12
When the exception was thrown, this was the stack: 
#0      ScrollPosition.pixels (package:flutter/src/widgets/scroll_position.dart:166:31)
#1      PagePosition.restoreScrollOffset (package:union_tabs/src/notification/scroll_position.dart:92:9)
#2      new ScrollPosition (package:flutter/src/widgets/scroll_position.dart:106:7)
#3      new ScrollPositionWithSingleContext (package:flutter/src/widgets/scroll_position_with_single_context.dart:55:8)
#4      new PagePosition (package:union_tabs/src/notification/scroll_position.dart:26:9)
...
═════════════════════════════════════════════════════════════════════════════════

**Comment by israrwz** [comment]
any fix for this?

**Comment by wilin52** [comment]
> any fix for this?

maybe the flutter version does not match, you can change version to 1.12
